# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (C) 2023  Jacob Koziej <jacobkoziej@gmail.com>

Import('env')
Import('python')
Import('venv')


env.PrependENVPath('LUA_PATH', Dir('lua').abspath + '/?', sep=';')
env.PrependENVPath('LUA_PATH', Dir('lua').abspath + '/?.lua', sep=';')

env['zgtc'] += Glob('lua/*.lua')


python_zgtc = Dir('python')

python_zgtc_src = [ ]

python_zgtc_src += [File('python/pyproject.toml')]
python_zgtc_src += Glob('python/zgtc/*.py')

requirements_zgtc = f'{venv[0].abspath}/.requirements_zgtc'

env['zgtc'] += env.Command(
    requirements_zgtc,
    python_zgtc_src,
    f'{python} -m pip install --editable {python_zgtc.path} && touch {requirements_zgtc}')
