# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (C) 2023  Jacob Koziej <jacobkoziej@gmail.com>

Import('env')


hello_world_sh = env.Substfile('hello-world.sh.in', SUBST_DICT={'@CC@' : '$CC'})
env.Depends(hello_world_sh, 'hello-world.c')

hello_world_output = env.CommandOutput(hello_world_sh)
env.SideEffect('a.out', hello_world_output)


run_hello_world_output = env.CommandOutput('run-hello-world.sh')
env.Depends(run_hello_world_output, hello_world_output)


compile_error_sh = env.Substfile('compile-error.sh.in', SUBST_DICT={'@CC@' : '$CC'})
env.Depends(compile_error_sh, 'compile-error-mock.c')

compile_error_output = env.CommandOutput([compile_error_sh, hello_world_sh])


env['zgtc'] += Glob('*.c')
env['zgtc'] += hello_world_sh
env['zgtc'] += hello_world_output
env['zgtc'] += run_hello_world_output
env['zgtc'] += compile_error_sh
env['zgtc'] += compile_error_output
