# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (C) 2023  Jacob Koziej <jacobkoziej@gmail.com>

Import('env')
Import('version')


version_tex = env.Substfile(
    'version.tex.in',
    SUBST_DICT={'@VERSION@' : version})
env.AlwaysBuild(version_tex)
