# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (C) 2023  Jacob Koziej <jacobkoziej@gmail.com>

Import('env')
Import('version')


env.AppendENVPath('LUA_PATH', Dir('.').abspath + '/?', sep=';')
env.AppendENVPath('LUA_PATH', Dir('.').abspath + '/?.lua', sep=';')


zgtc_src = [ ]

Export('zgtc_src')


version_tex = env.Substfile(
    'version.tex.in',
    SUBST_DICT={'@VERSION@' : version})
env.AlwaysBuild(version_tex)


zgtc_src += Glob('*.tex', exclude='zoomer-guide-to-c.tex')
zgtc_src += version_tex
zgtc_src += ['zgtc.lua']


SConscript([
    'preface.d/SConscript',
])


zgtc = env.PDF('zoomer-guide-to-c.tex')
env.Depends(zgtc, zgtc_src)
